########## Copyright C 2026 MIT Emad-ms ##########

# project: yuz-os runtime module
# project git : https://github.com/emad1234-msoudi/Yuz-OS_edu

# /opt/yuz-os/scripts/brand/grub_brand.conf

# build-time configuration for grub theme module.
# This configuration for grub_brand.sh script to install Yuz-os os barnd grub theme

########### setup environment ##########

#source "../../bootstrap.sh" #-> this source just for development

########## Configurable defaults ##########

# Minimal required packages for grub themes and extraction
GRUB_REQUIRED_PACKAGES=(
  grub-common
  unzip
)

# Grub Theme Manifest
GRUB_DATA="${DATA_DIR}/theme/grub_theme.zip"
GRUB_TARGET_DIR="/usr/share/grub/themes"

# Name of the theme directory inside ZIP
GRUB_THEME_NAME="Yuz-grub-theme"
GRUB_SELECTED_DIR="${GRUB_TARGET_DIR}/${GRUB_THEME_NAME}"
GRUB_THEME_FILE="${GRUB_SELECTED_DIR}/theme.txt"

# Modern Grub drop-in configuration path
GRUB_DROPIN_CONF="/etc/default/grub.d/99-yuz-theme.cfg"