########## Copyright C 2026 MIT Emad-ms ##########

# project: yuz-os runtime module
# project git : https://github.com/emad1234-msoudi/Yuz-OS_edu

# /opt/yuz-os/scripts/brand/os_brand.conf

# build time configuration for Yuz-OS module branding & information.
# This configuration for os_brand.sh to set :

# - /etc/os-release , modern linux information.
# - /etc/lsb-release , classic linux information file.
# - /etc/issue & /etc/issue.net for TTY or SSH Walcome !

########### setup environment ##########

#source "../../bootstrap.sh" #-> this source just for development

########## Configurable defaults ##########

# Yuz-OS Edu - Branding  Configuration

# OS RELEASE paths & templates
OS_RELEASE_FILE="/etc/os-release"
OS_RELEASE_TARGET_FILE="/usr/lib/os-release"

# We use single quotes to defer expansion until generation time in brand.sh.
# Double quotes inside the templates are preserved for standard key=value syntax.
OS_RELEASE_CONTENT='NAME="${PROJECT_FULL_NAME}"
VERSION="${PROJECT_VERSION} (${PROJECT_RELEASE})"
ID="${PROJECT_ID}"
ID_LIKE="debian"
PRETTY_NAME="${PROJECT_PRETTY_NAME}"
VERSION_ID="${PROJECT_VERSION}"
VERSION_CODENAME="${BASE_DISTRO_CODENAME}"
HOME_URL="${PROJECT_WEBSITE}"
SUPPORT_URL="${PROJECT_SUPPORT_URL}"
BUG_REPORT_URL="${PROJECT_BUG_REPORT_URL}"'

# LSB RELEASE paths & templates

LSB_RELEASE_FILE="/etc/lsb-release"

LSB_RELEASE_CONTENT='DISTRIB_ID="${PROJECT_NAME}"
DISTRIB_RELEASE="${PROJECT_VERSION}"
DISTRIB_CODENAME="${BASE_DISTRO_CODENAME}"
DISTRIB_DESCRIPTION="${PROJECT_DESCRIPTION}"'

# ISSUE paths & templates (Local TTY logins)

# Note: \\n and \\l are escaped so they pass raw into the final file,
# allowing agetty to interpret them as newline and tty line.

ISSUE_FILE="/etc/issue"

ISSUE_CONTENT='${PROJECT_PRETTY_NAME} \\n \\l'

# ISSUE NET paths & templates (Network/SSH logins)

ISSUE_NET_FILE="/etc/issue.net"

ISSUE_NET_CONTENT='${PROJECT_PRETTY_NAME}'

########## end ##########