########## Copyright C 2026 MIT Emad-ms ##########

# project: yuz-os runtime module
# project git : https://github.com/emad1234-msoudi/Yuz-OS_edu

# /opt/yuz-os/scripts/brand/plymouth_brand.conf

# build-time configuration for plymouth theme module.
# This configuration for plymouth_brand.sh script to install Yuz-os os barnd plymouth theme

########### setup environment ##########

#source "../../bootstrap.sh" #-> this source just for development

########## Configurable defaults ##########

# Minimal required packages for plymouth themes and extraction
PLYMOUTH_REQUIRED_PACKAGES=(
  plymouth
  unzip
)

# plymouth Theme Manifest
PLYMOUTH_DATA="${DATA_DIR}/theme/plymouth_theme.zip"
PLYMOUTH_TARGET_DIR="/usr/share/plymouth/themes"

# Name of the theme directory inside ZIP
PLYMOUTH_THEME_NAME="yuz-plymouth-theme"
PLYMOUTH_SELECTED_DIR="${PLYMOUTH_TARGET_DIR}/${PLYMOUTH_THEME_NAME}"
PLYMOUTH_THEME_FILE="${PLYMOUTH_SELECTED_DIR}/${PLYMOUTH_THEME_NAME}.plymouth"

# Modern plymouth drop-in configuration path
# PLYMOUTH_DROPIN_CONF="/etc/default/PLYMOUTH.d/99-yuz-theme.cfg"