#!/bin/bash

########## Copyright C 2026 MIT Emad-ms ##########

# project: yuz-os builder
# project git : https://github.com/emad1234-msoudi/Yuz-OS_edu

########## set terminal ##########

set -Eeuo pipefail # set termainl mo

########## config code ##########

sudo lb config \
  --distribution trixie \
  --architectures amd64 \
  --linux-flavours amd64 \
  --binary-images iso-hybrid \
  --debian-installer none \
  --archive-areas "main " \
  --mirror-bootstrap "https://mirror.mobinhost.com/debian/" \
  --mirror-chroot "https://mirror.mobinhost.com/debian/" \
  --mirror-binary "https://mirror.mobinhost.com/debian/" \
  --mirror-chroot-security "http://mirror.mobinhost.com/debian-security/" \
  --mirror-binary-security "http://mirror.mobinhost.com/debian-security/" \
  --bootloader "grub-efi grub-pc" \
  --chroot-squashfs-compression-type zstd \
  --compression xz \
  --initramfs-compression gzip \
  --firmware-chroot false \
  --firmware-binary false \
  --image-name "Yuz-OS_1.0.1_Educational" \
  --iso-volume "Yuz-OS 1.0.1 Educational" \
  --iso-publisher "Yuz-OS Project <https://github.com/emad1234-msoudi>" \
  --iso-application "Yuz-OS Live with Calamares Installer" \
  --bootappend-live "boot=live components persistence quiet splash locales=en_US.UTF-8 keyboard-layouts=us,fa" \
  --bootappend-install "quiet splash" \
  --cache true \
  --cache-packages true \
  --cache-indices true \
  --apt-secure true \
  --color \
  --verbose \
  --checksums sha256 \
  --uefi-secure-boot auto \
  --memtest none



