########## Copyright C 2026 MIT Emad-ms ##########

# project: yuz-os runtime module
# project git : https://github.com/emad1234-msoudi/Yuz-OS_edu

# /opt/yuz-os/scripts/style/style.sh

# build time configuration for GNOME defaults on Debian 13 / GNOME 48
# This configuration for style.sh script to installs user-changeable desktop defaults for GNOME, libadwaita, and Qt.
# It does not lock settings, so users can still modify them later.

########### setup environment ##########

#source "../../bootstrap.sh" #-> this source just for development

########## Configurable defaults ##########

ENVIRONMENT_DIR="/etc/environment.d"
SKEL_DIR="/etc/skel"

STYLE_REQUIRED_PACKAGES=(
  dconf-cli
  fontconfig
  flatpak
  qgnomeplatform-qt5
  qgnomeplatform-qt6
  adwaita-qt
  adwaita-qt6
  unzip
)

# GTK Theme Manifest

THEME_DATA="${DATA_DIR}/theme/gtk_theme.zip"
THEME_TARGET_DIR="/usr/share/themes"
THEME_LIGHT="Graphite-yellow-Light-nord"
THEME_DARK="Graphite-blue-Dark-nord"

THEME_SELECTED_NAME="${THEME_LIGHT}"
THEME_SELECTED_DIR="${THEME_TARGET_DIR}/${THEME_SELECTED_NAME}"

GTK4_SKEL_DIR="${SKEL_DIR}/.config/gtk-4.0"
GTK3_SKEL_DIR="${SKEL_DIR}/.config/gtk-3.0"
GTK4_THEME_DIR="${THEME_SELECTED_DIR}/gtk-4.0"

# Icon Theme Manifest

ICON_DATA="${DATA_DIR}/icons/icons.zip"
ICON_TARGET_DIR="/usr/share/icons"
ICON_LIGHT="Colloid-Nord-Light"
ICON_DARK="${ICON_LIGHT}" # fallback

ICON_SELECTED_NAME="${ICON_LIGHT}"
ICON_SELECTED_DIR="${ICON_TARGET_DIR}/${ICON_SELECTED_NAME}"

# Cursor Manifest

CURSOR_DATA="${DATA_DIR}/cursor/cursor.zip"
CURSOR_TARGET_DIR="/usr/share/icons"
CURSOR_LIGHT="Bibata-Modern-Ice"
CURSOR_DARK="$CURSOR_LIGHT" # fallback

CURSOR_SELECTED_NAME="$CURSOR_LIGHT"
CURSOR_SELECTED_DIR="${CURSOR_TARGET_DIR}/${CURSOR_SELECTED_NAME}"

# Wallpaper Manifest

# NOTE : refactor(brand): move Wallpaper assets to yuz-branding-base
# NOTE : These vars just set theme with dconf

#WALLPAPER_DATA="${DATA_DIR}/wallpaper/wallpapers.zip"
#WALLPAPER_TARGET_DIR="/usr/share/backgrounds/yuz"

BRANDING_WALLPAPER_DIR="/usr/share/desktop-base/yuz-branding/wallpaper"

WALLPAPER_LIGHT_URI="file://${BRANDING_WALLPAPER_DIR}/gnome-background-light.xml"
WALLPAPER_DARK_URI="file://${BRANDING_WALLPAPER_DIR}/gnome-background-dark.xml"
WALLPAPER_OPTIONS="zoom"

# Font Manifest

FONT_DATA="${DATA_DIR}/fonts/fonts.zip"
FONT_TARGET_DIR="/usr/local/share/fonts"

# Extensions 

EXTENSIONS_LIST=(
  'GPaste@gnome-shell-extensions.gnome.org'
  'user-theme@gnome-shell-extensions.gcampax.github.com'
  'dash-to-panel@jderose9.github.com'
  'ding@rastersoft.com'
  'gsconnect@andyholmes.github.io'
  'drive-menu@gnome-shell-extensions.gcampax.github.com'
)

EXTENSIONS_TARGET_DIR="/usr/share/gnome-shell/extensions"

# Dconf configuration

DCONF_PROFILE_DIR="/etc/dconf/profile"
DCONF_DB_DIR="/etc/dconf/db/local.d"
DCONF_PROFILE_FILE="${DCONF_PROFILE_DIR}/user"
DCONF_DEFAULTS_FILE="${DCONF_DB_DIR}/00-yuz-defaults"

# Qt style configuration

QT_ENV_FILE="${ENVIRONMENT_DIR}/90-yuz-qt.conf"

# Gnome style configuration

COLOR_SCHEME="prefer-light"

# System language configuration

INPUT_SOURCES="[('xkb', 'us'), ('xkb', 'fa')]"
XKB_OPTIONS="['grp:alt_shift_toggle']"

# Style data directories list

STYLE_DATA_DIRS=(
  "$(dirname "${THEME_DATA}")"
  "$(dirname "${ICON_DATA}")"
  "$(dirname "${CURSOR_DATA}")"
  "$(dirname "${WALLPAPER_DATA}")"
  "$(dirname "${FONT_DATA}")"
)


# Data list files 

STYLE_DATA_FILES=(
  "$THEME_DATA"
  "$ICON_DATA"
  "$CURSOR_DATA"
  "$WALLPAPER_DATA"
  "$FONT_DATA"
)

########## end ##########
